[build]
command = "hugo"
publish = "public"

[build.environment]
HUGO_VERSION = "0.120.0"
HUGO_ENABLEGITINFO = "true"

[dev]
command = "hugo server -D"
port = 1313
framework = "hugo"

[[headers]]
for = "/**"
[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"
